language: php
php:
- 7.2
before_script:
  - composer install
script: phpunit tests
deploy:
	provider: heroku
	app: jvadaw
	on: master
	skip_cleanup: true
	api_key: 1070dd53-671c-496b-a034-87989106f945
	secure: 0CZabSnEk/zy4JhXiWXdyRbnatCJ/jl3OsE80wYQfmh6dG9+9nKq11hjNCkRspiQdQdE6yF8p8UXSaE3pAlFMSkvNH257xUq+H9kwkP8if0xn0Wkqm4pU7T5gv6eMu7dQjhWnYrEwiUIrAHVWaB+Q6R71GNwiJaf6hCawO15FcSXetFcDO8qf7fLg7J5Oiu03rkcYooPZdq9ukofHyluPuXGAhigXLZ23RQF5inyxabMMx5dD0FJZD/I9zFnu/IgVA5Y+bqyPdusPtWID/2eTty0vKyJRTme84odH5rMRaeDKAlyaB5VwEK3Q6Yba9lHHtAvGCSAlAC5L1CVX1FES+pjqKZeUumJkJXSCndnzNJQukXNhQpMzCzl3IdhgfbvRl5U/Wo0+VYeDgy7dhmKUZwi4EF8h8GGu3v/0+XrUFu0NnSkqXBJ9yUyD5r74ou1Ein8TDYbMZCopbvV2XszcRJlwvr7t8ST3j+0WbWSlYQfeKYl0vGxhpu0h62Zs+VLlFqgBWFN3/mVyBTkktVWSZlodRAnANAe3jVBfgAKL5dpDyJLSDN1VZvc/i0T79zcrQJaAR3WNKZKce4ISITFkSE1evkb0BUeeYuHqCyqffkjuqwawEDXKrMuzkQ7x3DHJs2rGVWJPulscLIx823vw3Nroirvc6qnWPUFn60G00U=
